site_name: Tom PIT Connected Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - English: en/index.md
  - Slovenščina: sl/index.md
