site_name: Tom PIT Connected Documentation

repo_url: https://github.com/Tom-PIT/Connected.Docs/tree/main

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  
  favicon: img/favicon.ico
  
  palette:
    primary: blue
    accent: blue gray
  
  icon:
    logo: material/office-building
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - callouts

markdown_extensions:
  - md_in_html
  - admonition
  - tables
  - toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - English:
      - Introduction: en/index.md
      - Getting started: en/GettingStarted/00.GettingStarted.md
      - Common features: en/Common/Common.md
      - Production: en/Domains/Production/ProductionDomain.md
  - Slovenščina: sl/index.md
